### PR TITLE
pure functions & postfixes

### PR DESCRIPTION
**Pull request by amadare42**

### CODE REVIEW

**Comment by amadare42** [comment]
Is something wrong with the commit? You didn't reject it, so I don't know status of merge request.

**Comment by RafaelSalguero** [comment]
We need to refactor out all references to the workspace configuration to function arguments, leaving all functions pure, and loading the configuration as a single object that is loaded on the body of the activate method.

This for preserving function pureness

**Comment by amadare42** [comment]
Well, I thought that dragging configuration object all the way through all function starting would add needless complexity. Since it is javascript, you can easily replace any calls with mocks, so it shouldn't create any issues for such as small project... But okay, let's be as pure as possible. :)
So.. Is this version okay for you?

**Comment by RafaelSalguero** [comment]
Perfect! Thanks, I'll upload the next version in a few hours

**Comment by amadare42** [comment]
Sorry for reminding you, but there it was 12 days since pull. Maybe I can help you with something to boost release process?

**Comment by RafaelSalguero** [comment]
Sorry I had a busy week and completely forget it. Uploading the new version right now. Thanks :)

**Comment by RafaelSalguero** [comment]
Done

**Pull request merged**
